persons:
    resource: Home\MyPractoBundle\Controller\PersonsController
    type: rest

persons_constrained:
    resource: Home\MyPractoBundle\Controller\PersonsController
    type:     annotation
    defaults: {_format: json}
    requirements:
        personId: \d+
        _format: json|html|pdf